#!/bin/bash
#Auto setup file for apache webserver created by Jesse Laning

echo -e "\033[32mWelcome to the auto install script for an Apache2 RaspberryPi webserver\033[0m"
echo ""
echo ""

function ask {
    read -n 1 -r -p "$1"
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
            return 1;
    else
            exit
            echo "Abort.."
    fi
}

printf "This script automatically downloads and installs the required items for a RaspberryPi webserver: \033[36mApache2, php5, mySQL, phpMyAdmin, vsftpd (FTP Server), and Hexxeh's RPI update tool. It also sets up the SSH Server. Would you like to continue? [Y/n]\033[0m"

ask

echo ""
echo ""
echo "Continuing withing install"
echo ""
echo ""
echo -e "\033[93mNotice this still requires your input to completely setup and it may take a while to download everything."
echo -e "\033[93mMake sure you have a reliable internet connection.\033[0m"
echo ""
echo ""
sleep 3

#software updates
echo ""
echo ""
echo "Updating RaspberryPi software"
echo ""
echo ""
sudo dpkg-reconfigure tzdata
sudo apt-get update
sudo apt-get upgrade

#downloads and installs Hexxeh's RPI update tool
echo ""
echo ""
echo "Downloading Hexxeh's RPI update tool."
echo ""
echo ""
sudo apt-get install ca-certificates
sudo apt-get install git-core
sudo wget http://goo.gl/1BOfJ -O /usr/bin/rpi-update && sudo chmod +x /usr/bin/rpi-update
sudo rpi-update

#installs apache2 and php5
echo ""
echo ""
echo "Downloading Apache2 and Php5"
echo ""
echo ""
sudo apt-get install apache2 php5 libapache2-mod-php5
sudo service apache2 restart

#installs mySQL
echo ""
echo ""
echo "Downloading mySQL"
echo ""
echo ""
sudo apt-get install mysql-server mysql-client php5-mysql

#installs vsftpd (ftp server)
echo ""
echo ""
echo "Downloading vsftpd (FTP server)"
echo ""
echo ""
sudo chown -R pi /var/www
sudo apt-get install vsftpd
#writing vsftpd config file
sudo echo -e "listen=YES\nanonymous_enable=NO\nlocal_enable=YES\nwrite_enable=YES\ndirmessage_enable=YES\nuse_localtime=YES\nxferlog_enable=YES\nconnect_from_port_20=YES\nftpd_banner=Thank you for using the RPiWebServer tool created by Jesse Laning.\nsecure_chroot_dir=/var/run/vsftpd/empty\npam_service_name=vsftpd\nrsa_cert_file=/etc/ssl/private/vsftpd.pem\nforce_dot_files=YES\n" > "/etc/vsftpd.conf"
sudo service vsftpd restart

#Taking control of the web files so people can access them
sudo adduser pi www-data
sudo passwd www-data
sudo chown pi:www-data -R /var/www
sudo chmod 0755 -R /var/www
sudo chmod g+s -R /var/www

#installs phpMyAdmin
echo ""
echo ""
echo "Downloading phpmyadmin"
echo ""
echo ""
sudo apt-get install phpmyadmin
sudo echo -e "\nInclude /etc/phpmyadmin/apache.conf" >> "/etc/apache2/apache2.conf"
sudo service apache2 restart

#writes index.html file
sudo echo -e "<html>\n<head>\n<title>It works!</title>\n</head>\n<body>\n<h1>It works!</h1>\n<h2>Your first webpage on your RaspberryPi.</h2>\n<h3>Thank you for using the RPi-WebServer tool created by Jesse Laning.</h3>\n</body>\n</html>" > "/var/www/index.html"

printf "\033[93mTo finish installing a restart of the RaspberryPi is required\nRestart now? [Y/n]"

ask

sudo reboot
